Add cancel functionality to vesting contracts
Arrow-air/Arrow-Contracts pull request #34
Opened 2022-05-25 01:00 UTC by BrassLion

This change adds the ability for an owner of vesting contracts to cancel the vesting schedule of
a token or ETH that is currently locked within it, returning unvested tokens back to the owner.

Vesting contracts retain the address of their deployer and read ownership from the factory that
deployed them, allowing one ownership transfer to effect all deployed vesting contracts.

2022-05-26 01:23 UTC, GoodluckH requested changes
LGTM. Just a minor typo for the documentation.

Would be helpful to add an explanation in the doc to clarify under what circumstances would one want to call `updateFactory`.  Should we expect this to be called on an individual contract basis, or should we expect it to be called across all deployed contracts?

2022-05-26 01:23 UTC, GoodluckH commented on contracts/ArrowVestingBase.sol
> +        @notice Cancels the vesting contract, releasing vested tokens to the beneficiary and unvested ETH back to the factory owner.
```suggestion
        @notice Cancels the vesting contract, releasing vested tokens to the beneficiary and unvested tokens back to the factory owner.
```

2022-05-26 19:18 UTC, BrassLion commented
> Would be helpful to add an explanation in the doc to clarify under what circumstances would one want to call `updateFactory`. Should we expect this to be called on an individual contract basis, or should we expect it to be called across all deployed contracts? How does it effect all deployed contracts on one ownership transfer?

I've added a line of text to hopefully add the clarification you wanted. 👍

2022-05-26 20:16 UTC, GoodluckH approved these changes
GTG!

2022-05-26 20:16 UTC, GoodluckH commented on contracts/ArrowVestingBase.sol
> +        @notice Cancels the vesting contract, releasing vested tokens to the beneficiary and unvested ETH back to the factory owner.
```suggestion
        @notice Cancels the vesting contract, releasing vested tokens to the beneficiary and unvested tokens back to the factory owner.
```

2022-05-27 19:20 UTC, BrassLion commented
@GoodluckH Can you approve this if you're happy with it? Thanks.

2022-05-27 21:44 UTC, GoodluckH commented
@BrassLion  I already gave you the approval. I think it's @thomasgarrison 's approval that is needed.

2022-05-28 01:29 UTC, merged