Implement L2 Token Contracts for Optimism
Arrow-air/Arrow-Contracts pull request #38
Opened 2022-06-13 00:00 UTC by GoodluckH

A new deployment script is added to support L2 token creation on Optimism networks. 

Added several fields to `.env.example` for L2 token deployment related secrets/variables.

Run `npm run deployL2TokenOptimismKovan` to test out L2 token contract creation.

Also added a note to `README` to address an build cache related issue when verifying contracts.

2022-06-16 02:01 UTC, BrassLion requested changes

2022-06-16 02:01 UTC, BrassLion commented on .env.example
> +L2_TOKEN_SYMBOL=ARROW
Let's hardcode these into the deployment script. There's no way they'd change compared to L1.

2022-06-16 02:01 UTC, BrassLion commented on README.md
> +*Note: You may need to run `npx hardhat clean` to clear all the build caches and artifacts if you encounter "no such file or directory" issues when verifying contracts (also see [here](https://github
Did you find this solution after a pretty quick google? If so, we can probably remove this from the codebase, or move it to an issue if we really want to keep track of it.

2022-06-16 02:01 UTC, BrassLion commented on deploy/deployArrowTokenL2.js
> +  );
This can only be run on Optimism, so a check that we are running on the right chain would be useful here.

2022-06-19 22:19 UTC, BrassLion approved these changes
LGTM

2022-06-19 22:19 UTC, BrassLion commented
It would be great if we could get the tests passing.

2022-06-20 01:14 UTC, GoodluckH commented
Thanks. Resolved all the conflicts in `package-lock.json` that's causing the test CLI to fail.

2022-06-20 01:14 UTC, merged